/*! START TRANSACTION */;
CREATE TABLE gwas_to_iwas (
  gwa_element_id CHARACTER VARYING(20) NOT NULL,
  iwa_element_id CHARACTER VARYING(20) NOT NULL,
  iwa_element_name CHARACTER VARYING(150) NOT NULL,
  PRIMARY KEY (iwa_element_id),
  FOREIGN KEY (gwa_element_id) REFERENCES content_model_reference(element_id),
  FOREIGN KEY (iwa_element_id) REFERENCES content_model_reference(element_id),
  FOREIGN KEY (iwa_element_name) REFERENCES content_model_reference(element_name));
/*! COMMIT */;
/*! START TRANSACTION */;

INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.a.1', '4.A.1.a.1.a', 'Study details of artistic productions.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.a.1', '4.A.1.a.1.b', 'Read documents or materials to inform work processes.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.a.1', '4.A.1.a.1.c', 'Investigate criminal or legal matters.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.a.1', '4.A.1.a.1.d', 'Gather information from physical or electronic sources.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.a.1', '4.A.1.a.1.e', 'Consult legal materials or public records.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.a.1', '4.A.1.a.1.f', 'Gather data about operational or development activities.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.a.1', '4.A.1.a.1.g', 'Obtain information about goods or services.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.a.1', '4.A.1.a.1.h', 'Research issues related to earth sciences.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.a.1', '4.A.1.a.1.i', 'Research organizational behavior, processes, or performance.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.a.1', '4.A.1.a.1.j', 'Investigate the environmental impact of industrial or development activities.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.a.1', '4.A.1.a.1.k', 'Gather information for news stories.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.a.1', '4.A.1.a.1.l', 'Collect information about patients or clients.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.a.1', '4.A.1.a.1.m', 'Research agricultural processes or practices.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.a.1', '4.A.1.a.1.n', 'Collect data about consumer needs or opinions.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.a.1', '4.A.1.a.1.o', 'Investigate individuals'' background, behavior, or activities.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.a.1', '4.A.1.a.1.p', 'Research biological or ecological phenomena.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.a.1', '4.A.1.a.1.q', 'Obtain formal documentation or authorization.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.a.1', '4.A.1.a.1.r', 'Research historical or social issues.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.a.1', '4.A.1.a.1.s', 'Research healthcare issues.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.a.1', '4.A.1.a.1.t', 'Research technology designs or applications.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.a.1', '4.A.1.a.1.u', 'Investigate incidents or accidents.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.a.1', '4.A.1.a.1.v', 'Investigate organizational or operational problems.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.a.1', '4.A.1.a.1.w', 'Interview people to obtain information.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.a.2', '4.A.1.a.2.a', 'Monitor equipment operation.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.a.2', '4.A.1.a.2.b', 'Monitor operations to ensure adequate performance.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.a.2', '4.A.1.a.2.c', 'Monitor financial data or activities.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.a.2', '4.A.1.a.2.d', 'Monitor traffic conditions.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.a.2', '4.A.1.a.2.e', 'Monitor health conditions of humans or animals.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.a.2', '4.A.1.a.2.f', 'Monitor individual behavior or performance.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.a.2', '4.A.1.a.2.g', 'Monitor safety or security of work areas, facilities, or properties.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.a.2', '4.A.1.a.2.h', 'Monitor external affairs, trends, or events.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.a.2', '4.A.1.a.2.i', 'Monitor environmental conditions.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.a.2', '4.A.1.a.2.j', 'Monitor operation of computer or information technologies.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.a.2', '4.A.1.a.2.k', 'Monitor operations to ensure compliance with regulations or standards.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.b.1', '4.A.1.b.1.a', 'Mark materials or objects for identification.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.b.1', '4.A.1.b.1.b', 'Identify business or organizational opportunities.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.b.2', '4.A.1.b.2.a', 'Administer diagnostic tests to assess patient health.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.b.2', '4.A.1.b.2.b', 'Evaluate green technologies or processes.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.b.2', '4.A.1.b.2.c', 'Test characteristics of materials or products.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.b.2', '4.A.1.b.2.d', 'Inspect vehicles.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.b.2', '4.A.1.b.2.e', 'Inspect facilities or equipment.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.b.2', '4.A.1.b.2.f', 'Inspect completed work or finished products.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.b.2', '4.A.1.b.2.g', 'Inspect commercial, industrial, or production systems or equipment.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.b.2', '4.A.1.b.2.h', 'Test performance of computer or information systems.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.b.2', '4.A.1.b.2.i', 'Examine people or animals to assess health conditions or physical characteristics.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.b.2', '4.A.1.b.2.j', 'Inspect characteristics or conditions of materials or products.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.b.2', '4.A.1.b.2.k', 'Test sites or materials for environmental hazards.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.b.2', '4.A.1.b.2.l', 'Test performance of equipment or systems.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.b.3', '4.A.1.b.3.a', 'Measure physical characteristics of materials, products, or equipment.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.b.3', '4.A.1.b.3.b', 'Estimate project development or operational costs.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.b.3', '4.A.1.b.3.c', 'Calculate financial data.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.b.3', '4.A.1.b.3.d', 'Assess characteristics of land or property.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.1.b.3', '4.A.1.b.3.e', 'Take physical measurements of patients or clients.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.a.1', '4.A.2.a.1.a', 'Assess living, work, or social needs or status of individuals or communities.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.a.1', '4.A.2.a.1.b', 'Evaluate programs, practices, or processes.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.a.1', '4.A.2.a.1.c', 'Assess student capabilities, needs, or performance.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.a.1', '4.A.2.a.1.d', 'Evaluate personnel capabilities or performance.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.a.1', '4.A.2.a.1.e', 'Evaluate production inputs or outputs.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.a.1', '4.A.2.a.1.f', 'Evaluate patient or client condition or treatment options.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.a.1', '4.A.2.a.1.g', 'Evaluate the characteristics, usefulness, or performance of products or technologies.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.a.1', '4.A.2.a.1.h', 'Evaluate scholarly work.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.a.1', '4.A.2.a.1.i', 'Evaluate condition of financial assets, property, or other resources.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.a.1', '4.A.2.a.1.j', 'Evaluate project feasibility.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.a.2', '4.A.2.a.2.a', 'Evaluate the quality or accuracy of data.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.a.2', '4.A.2.a.2.b', 'Sort materials or products.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.a.2', '4.A.2.a.2.c', 'Compile records, documentation, or other data.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.a.2', '4.A.2.a.2.d', 'Reconcile financial data.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.a.2', '4.A.2.a.2.e', 'Verify personal information.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.a.3', '4.A.2.a.3.a', 'Examine materials or documentation for accuracy or compliance.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.a.3', '4.A.2.a.3.b', 'Assess compliance with environmental standards or regulations.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.a.3', '4.A.2.a.3.c', 'Examine financial activities, operations, or systems.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.a.3', '4.A.2.a.3.d', 'Follow standard healthcare safety procedures to protect patient and staff members.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.a.4', '4.A.2.a.4.a', 'Analyze environmental or geospatial data.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.a.4', '4.A.2.a.4.b', 'Analyze market or industry conditions.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.a.4', '4.A.2.a.4.c', 'Analyze business or financial risks.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.a.4', '4.A.2.a.4.d', 'Analyze scientific or applied data using mathematical principles.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.a.4', '4.A.2.a.4.e', 'Evaluate designs, specifications, or other technical data.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.a.4', '4.A.2.a.4.f', 'Analyze health or medical data.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.a.4', '4.A.2.a.4.g', 'Analyze data to improve operations.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.a.4', '4.A.2.a.4.h', 'Research laws, precedents, or other legal data.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.a.4', '4.A.2.a.4.i', 'Assess characteristics or impacts of regulations or policies.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.a.4', '4.A.2.a.4.j', 'Analyze biological or chemical substances or related data.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.a.4', '4.A.2.a.4.k', 'Analyze business or financial data.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.a.4', '4.A.2.a.4.l', 'Analyze performance of systems or equipment.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.1', '4.A.2.b.1.a', 'Determine values or prices of goods or services.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.1', '4.A.2.b.1.b', 'Diagnose system or equipment problems.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.1', '4.A.2.b.1.c', 'Authorize business activities or transactions.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.1', '4.A.2.b.1.d', 'Determine operational methods or procedures.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.1', '4.A.2.b.1.e', 'Make legal decisions.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.1', '4.A.2.b.1.f', 'Diagnose health conditions or disorders.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.1', '4.A.2.b.1.g', 'Edit written materials or documents.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.1', '4.A.2.b.1.h', 'Determine resource needs of projects or operations.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.1', '4.A.2.b.1.i', 'Implement procedures or processes.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.1', '4.A.2.b.1.j', 'Select materials or equipment for operations or projects.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.1', '4.A.2.b.1.k', 'Alter audio or video recordings.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.2', '4.A.2.b.2.a', 'Develop patient or client care or treatment plans.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.2', '4.A.2.b.2.b', 'Design computer or information systems or applications.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.2', '4.A.2.b.2.c', 'Develop business or marketing plans.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.2', '4.A.2.b.2.d', 'Develop recipes or menus.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.2', '4.A.2.b.2.e', 'Develop safety standards, policies, or procedures.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.2', '4.A.2.b.2.f', 'Design databases.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.2', '4.A.2.b.2.g', 'Develop plans for managing or preserving natural resources.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.2', '4.A.2.b.2.h', 'Develop financial or business plans.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.2', '4.A.2.b.2.i', 'Develop health assessment methods or programs.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.2', '4.A.2.b.2.j', 'Develop marketing or promotional materials.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.2', '4.A.2.b.2.k', 'Design materials or devices.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.2', '4.A.2.b.2.l', 'Develop educational programs, plans, or procedures.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.2', '4.A.2.b.2.m', 'Develop systems or practices to mitigate or resolve environmental problems.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.2', '4.A.2.b.2.n', 'Develop public or community health programs.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.2', '4.A.2.b.2.o', 'Create visual designs or displays.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.2', '4.A.2.b.2.p', 'Develop contingency or emergency response plans.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.2', '4.A.2.b.2.q', 'Develop sustainable organizational or business policies or practices.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.2', '4.A.2.b.2.r', 'Develop news, entertainment, or artistic content.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.2', '4.A.2.b.2.s', 'Develop research plans or methodologies.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.2', '4.A.2.b.2.t', 'Create artistic designs or performances.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.2', '4.A.2.b.2.u', 'Develop scientific or mathematical theories or models.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.2', '4.A.2.b.2.v', 'Develop organizational or program goals or objectives.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.3', '4.A.2.b.3.a', 'Maintain current knowledge in area of expertise.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.4', '4.A.2.b.4.a', 'Develop organizational policies, systems, or processes.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.4', '4.A.2.b.4.b', 'Draft legislation or regulations.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.5', '4.A.2.b.5.a', 'Prepare schedules for services or facilities.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.5', '4.A.2.b.5.b', 'Schedule operational activities.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.5', '4.A.2.b.5.c', 'Schedule appointments.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.6', '4.A.2.b.6.a', 'Plan events or programs.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.2.b.6', '4.A.2.b.6.b', 'Plan work activities.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.1', '4.A.3.a.1.a', 'Prepare mixtures or solutions.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.1', '4.A.3.a.1.b', 'Protect people or property from threats such as fires or flooding.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.1', '4.A.3.a.1.c', 'Clean tools, equipment, facilities, or work areas.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.1', '4.A.3.a.1.d', 'Set up protective structures or coverings near work areas.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.1', '4.A.3.a.1.e', 'Dispose of waste or debris.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.1', '4.A.3.a.1.f', 'Load products, materials, or equipment for transportation or further processing.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.1', '4.A.3.a.1.g', 'Perform general construction or extraction activities.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.1', '4.A.3.a.1.h', 'Clean workpieces, finished products, or other objects.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.1', '4.A.3.a.1.i', 'Clean medical equipment or facilities.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.1', '4.A.3.a.1.j', 'Move materials, equipment, or supplies.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.1', '4.A.3.a.1.k', 'Maintain safety or security.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.1', '4.A.3.a.1.l', 'Escort others.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.1', '4.A.3.a.1.m', 'Transport patients or clients.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.1', '4.A.3.a.1.n', 'Climb equipment or structures.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.1', '4.A.3.a.1.o', 'Provide food or beverage services.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.1', '4.A.3.a.1.p', 'Perform athletic activities for fitness, competition, or artistic purposes.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.1', '4.A.3.a.1.q', 'Perform agricultural activities.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.a', 'Build structures.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.b', 'Collect samples of products or materials.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.c', 'Prepare foods or beverages.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.d', 'Assemble equipment or components.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.e', 'Sew garments or materials.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.f', 'Position workpieces or materials on equipment.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.g', 'Shape materials to create products.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.h', 'Arrange displays or decorations.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.i', 'Adjust equipment to ensure adequate performance.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.j', 'Train animals.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.k', 'Prepare medical equipment or work areas for use.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.l', 'Cut materials.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.m', 'Prepare industrial materials for processing or use.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.n', 'Cut trees or other vegetation.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.o', 'Smooth surfaces of objects or equipment.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.p', 'Install energy or heating equipment.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.q', 'Fabricate medical devices.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.r', 'Direct vehicle traffic.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.s', 'Disassemble equipment.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.t', 'Install commercial or production equipment.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.u', 'Apply hygienic or cosmetic agents to skin or hair.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.v', 'Position tools or equipment.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.w', 'Tend watercraft.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.x', 'Adjust medical equipment to ensure adequate performance.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.y', 'Engrave objects.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.z', 'Embalm corpses.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.aa', 'Fabricate devices or components.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.ab', 'Create decorative objects or parts of objects.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.ac', 'Process animal carcasses.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.ad', 'Drill holes in earth or materials.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.ae', 'Groom or style hair.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.af', 'Set up classrooms, facilities, educational materials, or equipment.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.ag', 'Apply protective solutions or coatings.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.ah', 'Connect components or supply lines to equipment or tools.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.ai', 'Join parts using soldering, welding, or brazing techniques.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.aj', 'Assemble products or work aids.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.ak', 'Stock supplies or products.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.al', 'Collect environmental or biological samples.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.am', 'Apply materials to fill gaps or imperfections.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.an', 'Remove workpieces from production equipment.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.ao', 'Position materials or components for assembly.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.ap', 'Package objects.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.aq', 'Install plumbing or piping equipment or systems.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.ar', 'Hunt animals.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.as', 'Apply decorative finishes.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.at', 'Set up equipment.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.2', '4.A.3.a.2.au', 'Prepare specimens or materials for testing.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.3', '4.A.3.a.3.a', 'Operate office equipment.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.3', '4.A.3.a.3.b', 'Operate pumping systems or equipment.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.3', '4.A.3.a.3.c', 'Operate construction or excavation equipment.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.3', '4.A.3.a.3.d', 'Operate medical equipment.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.3', '4.A.3.a.3.e', 'Operate audiovisual or related equipment.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.3', '4.A.3.a.3.f', 'Operate industrial processing or production equipment.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.3', '4.A.3.a.3.g', 'Operate energy production or distribution equipment.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.3', '4.A.3.a.3.h', 'Operate lifting or moving equipment.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.3', '4.A.3.a.3.i', 'Operate laboratory or field equipment.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.3', '4.A.3.a.3.j', 'Operate communications equipment or systems.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.3', '4.A.3.a.3.k', 'Operate agricultural or forestry equipment.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.3', '4.A.3.a.3.l', 'Operate cutting or grinding equipment.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.a.4', '4.A.3.a.4.a', 'Operate transportation equipment or vehicles.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.1', '4.A.3.b.1.a', 'Program computer systems or production equipment.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.1', '4.A.3.b.1.b', 'Implement security measures for computer or information systems.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.1', '4.A.3.b.1.c', 'Set up computer systems, networks, or other information systems.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.1', '4.A.3.b.1.d', 'Resolve computer problems.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.1', '4.A.3.b.1.e', 'Operate computer systems or computerized equipment.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.1', '4.A.3.b.1.f', 'Process digital or online data.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.2', '4.A.3.b.2.a', 'Develop technical specifications for products or operations.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.2', '4.A.3.b.2.b', 'Design structures or facilities.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.2', '4.A.3.b.2.c', 'Design industrial systems or equipment.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.2', '4.A.3.b.2.d', 'Develop models of systems, processes, or products.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.2', '4.A.3.b.2.e', 'Design electrical or electronic systems or equipment.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.2', '4.A.3.b.2.f', 'Develop operational or technical procedures or standards.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.4', '4.A.3.b.4.a', 'Maintain facilities or equipment.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.4', '4.A.3.b.4.b', 'Repair workpieces or products.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.4', '4.A.3.b.4.c', 'Repair tools or equipment.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.4', '4.A.3.b.4.d', 'Repair vehicle components.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.4', '4.A.3.b.4.e', 'Maintain vehicles in working condition.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.4', '4.A.3.b.4.f', 'Maintain medical equipment or instruments.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.5', '4.A.3.b.5.a', 'Maintain tools or equipment.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.5', '4.A.3.b.5.b', 'Repair electrical or electronic equipment.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.5', '4.A.3.b.5.c', 'Maintain electronic, computer, or other technical equipment.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.6', '4.A.3.b.6.a', 'Prepare financial documents, reports, or budgets.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.6', '4.A.3.b.6.b', 'Record information about legal matters.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.6', '4.A.3.b.6.c', 'Present research or technical information.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.6', '4.A.3.b.6.d', 'Record information about environmental conditions.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.6', '4.A.3.b.6.e', 'Record images with photographic or audiovisual equipment.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.6', '4.A.3.b.6.f', 'Prepare health or medical documents.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.6', '4.A.3.b.6.g', 'Prepare proposals or grant applications.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.6', '4.A.3.b.6.h', 'Maintain operational records.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.6', '4.A.3.b.6.i', 'Document technical designs, procedures, or activities.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.6', '4.A.3.b.6.j', 'Maintain sales or financial records.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.6', '4.A.3.b.6.k', 'Maintain health or medical records.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.6', '4.A.3.b.6.l', 'Prepare informational or instructional materials.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.6', '4.A.3.b.6.m', 'Prepare documentation for contracts, applications, or permits.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.6', '4.A.3.b.6.n', 'Prepare legal or regulatory documents.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.6', '4.A.3.b.6.o', 'Prepare reports of operational or procedural activities.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.3.b.6', '4.A.3.b.6.p', 'Write material for artistic or commercial purposes.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.1', '4.A.4.a.1.a', 'Explain technical details of products or services.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.1', '4.A.4.a.1.b', 'Explain regulations, policies, or procedures.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.1', '4.A.4.a.1.c', 'Interpret language, cultural, or religious information for others.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.1', '4.A.4.a.1.d', 'Explain financial information.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.1', '4.A.4.a.1.e', 'Explain medical information to patients or family members.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.2', '4.A.4.a.2.a', 'Communicate environmental or sustainability information.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.2', '4.A.4.a.2.b', 'Assist scientists, scholars, or technical specialists with projects or research.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.2', '4.A.4.a.2.c', 'Communicate with others about operational plans or activities.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.2', '4.A.4.a.2.d', 'Confer with healthcare or other professionals about patient care.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.2', '4.A.4.a.2.e', 'Communicate with others about business strategies.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.2', '4.A.4.a.2.f', 'Collaborate in the development of educational programs.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.2', '4.A.4.a.2.g', 'Notify others of emergencies or problems.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.2', '4.A.4.a.2.h', 'Communicate with others about specifications or project details.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.2', '4.A.4.a.2.i', 'Discuss legal matters with clients, disputants, or legal professionals or staff.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.2', '4.A.4.a.2.j', 'Confer with clients to determine needs or order specifications.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.3', '4.A.4.a.3.a', 'Present information in legal proceedings.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.3', '4.A.4.a.3.b', 'Provide information or assistance to the public.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.3', '4.A.4.a.3.c', 'Provide information to guests, clients, or customers.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.4', '4.A.4.a.4.a', 'Develop professional relationships or networks.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.5', '4.A.4.a.5.a', 'Assist others to access additional services or resources.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.5', '4.A.4.a.5.b', 'Administer therapeutic treatments.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.5', '4.A.4.a.5.c', 'Administer basic health care or medical treatments.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.5', '4.A.4.a.5.d', 'Care for plants or animals.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.5', '4.A.4.a.5.e', 'Intervene in crisis situations or emergencies.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.5', '4.A.4.a.5.f', 'Fit assistive devices to patients or clients.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.5', '4.A.4.a.5.g', 'Administer emergency medical treatment.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.5', '4.A.4.a.5.h', 'Assist individuals with paperwork.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.5', '4.A.4.a.5.i', 'Assist individuals with special needs.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.5', '4.A.4.a.5.j', 'Provide general assistance to others, such as customers, patrons, or motorists.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.5', '4.A.4.a.5.k', 'Assist healthcare practitioners during medical procedures.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.5', '4.A.4.a.5.l', 'Treat injuries, illnesses, or diseases.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.6', '4.A.4.a.6.a', 'Advocate for individual or community needs.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.6', '4.A.4.a.6.b', 'Sell products or services.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.6', '4.A.4.a.6.c', 'Promote products, services, or programs.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.7', '4.A.4.a.7.a', 'Mediate disputes.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.7', '4.A.4.a.7.b', 'Negotiate contracts or agreements.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.7', '4.A.4.a.7.c', 'Resolve personnel or operational problems.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.8', '4.A.4.a.8.a', 'Present arts or entertainment performances.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.8', '4.A.4.a.8.b', 'Conduct amusement or gaming activities.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.a.8', '4.A.4.a.8.c', 'Respond to customer problems or inquiries.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.1', '4.A.4.b.1.a', 'Coordinate with others to resolve problems.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.1', '4.A.4.b.1.b', 'Signal others to coordinate work activities.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.1', '4.A.4.b.1.c', 'Coordinate activities with clients, agencies, or organizations.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.1', '4.A.4.b.1.d', 'Coordinate artistic or entertainment activities.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.1', '4.A.4.b.1.e', 'Coordinate group, community, or public activities.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.1', '4.A.4.b.1.f', 'Assign work to others.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.1', '4.A.4.b.1.g', 'Coordinate regulatory compliance activities.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.2', '4.A.4.b.2.a', 'Provide support or encouragement to others.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.3', '4.A.4.b.3.a', 'Teach life skills.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.3', '4.A.4.b.3.b', 'Teach academic or vocational subjects.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.3', '4.A.4.b.3.c', 'Teach safety procedures or standards to others.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.3', '4.A.4.b.3.d', 'Train others on operational or work procedures.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.3', '4.A.4.b.3.e', 'Train others to use equipment or products.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.3', '4.A.4.b.3.f', 'Train others on health or medical topics.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.4', '4.A.4.b.4.a', 'Supervise personnel activities.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.4', '4.A.4.b.4.b', 'Serve on organizational committees.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.4', '4.A.4.b.4.c', 'Manage agricultural or forestry operations.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.4', '4.A.4.b.4.d', 'Supervise activities in correctional facilities.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.4', '4.A.4.b.4.e', 'Direct scientific or technical activities.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.4', '4.A.4.b.4.f', 'Manage human resources activities.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.4', '4.A.4.b.4.g', 'Manage control systems or activities.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.4', '4.A.4.b.4.h', 'Manage budgets or finances.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.4', '4.A.4.b.4.i', 'Direct construction or extraction activities.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.4', '4.A.4.b.4.j', 'Direct organizational operations, activities, or procedures.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.4', '4.A.4.b.4.k', 'Direct security or safety activities or operations.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.4', '4.A.4.b.4.l', 'Direct legal activities.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.5', '4.A.4.b.5.a', 'Coach others.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.6', '4.A.4.b.6.a', 'Advise patients or clients on medical issues.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.6', '4.A.4.b.6.b', 'Advise others on products or services.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.6', '4.A.4.b.6.c', 'Advise others on environmental sustainability or green practices.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.6', '4.A.4.b.6.d', 'Advise others on the design or use of technologies.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.6', '4.A.4.b.6.e', 'Advise others on business or operational matters.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.6', '4.A.4.b.6.f', 'Advise others on healthcare or wellness issues.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.6', '4.A.4.b.6.g', 'Advise others on educational or vocational matters.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.6', '4.A.4.b.6.h', 'Advise others on legal or regulatory matters.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.6', '4.A.4.b.6.i', 'Advise others on workplace health or safety issues.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.6', '4.A.4.b.6.j', 'Counsel others about personal matters.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.b.6', '4.A.4.b.6.k', 'Advise others on financial matters.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.c.1', '4.A.4.c.1.a', 'Perform administrative or clerical activities.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.c.1', '4.A.4.c.1.b', 'Perform court-related or other legal administrative activities.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.c.1', '4.A.4.c.1.c', 'Execute financial transactions.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.c.1', '4.A.4.c.1.d', 'Issue documentation.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.c.1', '4.A.4.c.1.e', 'Process shipments or mail.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.c.1', '4.A.4.c.1.f', 'Process forensic or legal evidence.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.c.2', '4.A.4.c.2.a', 'Perform recruiting or hiring activities.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.c.2', '4.A.4.c.2.b', 'Perform human resources activities.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.c.3', '4.A.4.c.3.a', 'Replenish inventories of materials, equipment, or products.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.c.3', '4.A.4.c.3.b', 'Order medical tests or procedures.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.c.3', '4.A.4.c.3.c', 'Distribute materials, supplies, or resources.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.c.3', '4.A.4.c.3.d', 'Collect fares or payments.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.c.3', '4.A.4.c.3.e', 'Purchase goods or services.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.c.3', '4.A.4.c.3.f', 'Prescribe medical treatments or devices.');
INSERT INTO gwas_to_iwas (gwa_element_id, iwa_element_id, iwa_element_name) VALUES ('4.A.4.c.3', '4.A.4.c.3.g', 'Monitor resources or inventories.');
/*! COMMIT */;

